---
title: "Practicum_Two"
output:
  pdf_document: default
  html_notebook: default
---
# Create database schema
## Connect to database
```{r}
library(RSQLite)

dbFile = "./Practicum2.sqlite"

dbcon <- dbConnect(RSQLite::SQLite(), dbFile)
```

## Create table Author
```{sql connection=dbcon}
DROP TABLE IF EXISTS Author;
```

```{sql connection=dbcon}
CREATE TABLE Author (
  authorId INTEGER PRIMARY KEY,
  lastName TEXT,
  foreName TEXT,
  initials TEXT
);
```

## Create table Journal
```{sql connection=dbcon}
DROP TABLE IF EXISTS Journal;
```

```{sql connection=dbcon}
CREATE TABLE Journal (
  ISSN TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  isoabbreviation TEXT NOT NULL
);
```

## Create table JournalIssue
```{sql connection=dbcon}
DROP TABLE IF EXISTS JournalIssue;
```

```{sql connection=dbcon}
CREATE TABLE JournalIssue (
  jId INTEGER PRIMARY KEY,
  ISSN INTEGER REFERENCES Journal(ISSN) ON DELETE CASCADE,
  volume INTEGER NOT NULL,
  issue INTEGER NOT NULL,
  pubYear TEXT NOT NULL,
  pubMonth TEXT NOT NULL
);
```

## Create table AuthorShip
```{sql connection=dbcon}
DROP TABLE IF EXISTS AuthorShip;
```

```{sql connection=dbcon}
CREATE TABLE AuthorShip (
  articleId INTEGER,
  authorId INTEGER,
  PRIMARY KEY (articleId, authorId)
)
```

## Create table Article
```{sql connection=dbcon}
DROP TABLE IF EXISTS Article;
```

```{sql connection=dbcon}
CREATE TABLE Article (
  articleId INTEGER PRIMARY KEY,
  jId INTEGER REFERENCES JournalIssue(jId) ON DELETE CASCADE,
  pubMode TEXT NOT NULL,
  title TEXT NOT NULL,
  abstract TEXT NOT NULL
)
```


# Loading Libraries

```{r warning=FALSE}
library(XML)
library(xslt)
```

# Load XML data to database
## Read XML file
```{r}
xmlPath <- "./pubmed_sample.xml"
xmlDoc = read_xml(xmlPath)
```

## Load Journal table
```{r}
# Extract Journal Data
xslPath = "./journal.xsl"
xslDoc = read_xml(xslPath,package="xslt")
journal_raw = xml_xslt(xmlDoc,xslDoc)
journals = unique(xmlToDataFrame(XML::xmlParse(journal_raw)))
dbWriteTable(dbcon,name = "Journal", value = journals, append = TRUE)
```

## Load Author table
```{r}
# Extract Author Data
xslPath = "./author.xsl"
xslDoc = read_xml(xslPath,package="xslt")
author_raw = xml_xslt(xmlDoc,xslDoc)
authors = unique(xmlToDataFrame(XML::xmlParse(author_raw)))
authors = cbind(authorId=rownames(authors),authors)
dbWriteTable(dbcon,name = "Author", value = authors, append = TRUE)
```

## Load JournalIssue table
```{r}
# Extract JournalIssue Data
xslPath = "./journalIssue.xsl"
xslDoc = read_xml(xslPath,package="xslt")
journalIssue_raw = xml_xslt(xmlDoc,xslDoc)
journalIssues = unique(xmlToDataFrame(XML::xmlParse(journalIssue_raw)))
journalIssues = cbind(jId=rownames(journalIssues),journalIssues)
medDate <- journalIssues$medlineDate
for (i in 1 : 19) {
  if (medDate[i] != '') {
  pubDate <- strsplit(medDate[i],split = ' ')
  journalIssues$pubYear[i] = pubDate[[1]][1]
  journalIssues$pubMonth[i] = pubDate[[1]][2]
  }
}
journalIssues <- subset(journalIssues, select = -c(7))
dbWriteTable(dbcon,name = "JournalIssue", value = journalIssues, append = TRUE)
```

```{sql connection=dbcon}
SELECT * FROM JournalIssue;
```

## Load AuthorShip table
```{r}
# Extract AuthorShip Data
xslPath = "./AuthorShip.xsl"
xslDoc = read_xml(xslPath,package="xslt")
AuthorShip_raw = xml_xslt(xmlDoc,xslDoc)
AuthorShip = unique(xmlToDataFrame(XML::xmlParse(AuthorShip_raw)))
AuthorShip = cbind(authorId=rownames(AuthorShip),AuthorShip)

dbWriteTable(dbcon,name = "AuthorShip", value = AuthorShip, append = TRUE)
```

```{sql connection=dbcon}
SELECT * FROM AuthorShip WHERE authorId = articleId;
```

## Load Article table
```{r}
# Extract Article Data
xslPath = "./Article.xsl"
xslDoc = read_xml(xslPath,package="xslt")
article_raw = xml_xslt(xmlDoc,xslDoc)
article = unique(xmlToDataFrame(XML::xmlParse(article_raw)))
article = cbind(authorId=rownames(article),article)

dbWriteTable(dbcon,name = "Article", value = article, append = TRUE)
```
